/**
 * Mandelbulber v2, a 3D fractal generator  _%}}i*<.        ____                _______
 * Copyright (C) 2026 Mandelbulber Team   _>]|=||i=i<,     / __ \___  ___ ___  / ___/ /
 *                                        \><||i|=>>%)    / /_/ / _ \/ -_) _ \/ /__/ /__
 * This file is part of Mandelbulber.     )<=i=]=|=i<>    \____/ .__/\__/_//_/\___/____/
 * The project is licensed under GPLv3,   -<>>=|><|||`        /_/
 * see also COPYING file in this folder.    ~+{i%+++
 *
 * Pseudo Kleinian Trig, amoser's complex sine formula
 * @reference https://fractalforums.org/index.php?topic=5591.0;topicseen

 * This file has been autogenerated by tools/populateUiInformation.php
 * from the file "fractal_pseudo_kleinian_trig_v3.cpp" in the folder formula/definition
 * D O    N O T    E D I T    T H I S    F I L E !
 */

REAL4 PseudoKleinianTrigV3Iteration(REAL4 z, __global sFractalCl *fractal, sExtendedAuxCl *aux)
{ // info amoser's complex sine formula, DE by amoser
	REAL4 oldZ = z;
	REAL temp = 0.0f;

	// pi scale
	if (fractal->transformCommon.functionEnabledTFalse
			&& aux->i >= fractal->transformCommon.startIterationsT
			&& aux->i < fractal->transformCommon.stopIterationsT1)
	{
		temp = M_PI_F * fractal->transformCommon.scaleC1;
		z *= temp;
		aux->DE *= fabs(temp);
	}

	// sphere inversion (Pre-Trig)
	if (fractal->transformCommon.functionEnabledPFalse
			&& aux->i >= fractal->transformCommon.startIterationsP
			&& aux->i < fractal->transformCommon.stopIterationsP1)
	{
		z += fractal->mandelbox.offset;
		z *= fractal->transformCommon.scale;
		aux->DE = aux->DE * fabs(fractal->transformCommon.scale) + 1.0f;
		// Combine the magnitude-based inversion
		REAL invRR = 1.0f / dot(z, z);
		z *= invRR;
		aux->DE *= invRR;

		z -= fractal->mandelbox.offset + fractal->transformCommon.additionConstant000;
	}

	// 1.f Fold & Offset (Pre-Trig)
	if (aux->i >= fractal->transformCommon.startIterationsF
			&& aux->i < fractal->transformCommon.stopIterationsF)
	{
		if (fractal->transformCommon.functionEnabledAxFalse) z.x = fabs(z.x);
		if (fractal->transformCommon.functionEnabledAyFalse) z.y = fabs(z.y);
		if (fractal->transformCommon.functionEnabledAzFalse) z.z = fabs(z.z);
		z -= fractal->transformCommon.offsetA000;
	}

	// 2.f Trigonometry & Hyperbolics
	REAL sx, cx, sy, cy;
	// Use sincos to compute pairs in half the time
	sx = native_sin(z.x);
	cx = native_cos(z.x);
	sy = native_sin(z.y);
	cy = native_cos(z.y);

	REAL ez = exp(z.z);
	REAL invEz = 1.0f / (ez);
	REAL shz = 0.5f * (ez - invEz);
	REAL chz = 0.5f * (ez + invEz);

	// 3.f Pre-compute components for 'z' update
	REAL sxchz = sx * chz;
	REAL sychz = sy * chz;
	REAL cxcy_shz = (cx * cy) * shz;
	z = (REAL4){sxchz, sychz, cxcy_shz, 0.0f};

	if (fractal->transformCommon.rotationEnabledFalse
			&& aux->i >= fractal->transformCommon.startIterationsR
			&& aux->i < fractal->transformCommon.stopIterationsR)
		z = Matrix33MulFloat4(fractal->transformCommon.rotationMatrix, z);

	// 4.f Regulator
	if (fractal->transformCommon.functionEnabledHFalse)
	{
		// native_rsqrt is 3x faster
		REAL reg = 1.0f / native_sqrt(1.0f + (sx * sx * sy * sy));
		z *= reg;
		aux->DE *= reg;
	}

	// 5.f Transform & Stretch
	if (aux->i >= fractal->transformCommon.startIterationsS
			&& aux->i < fractal->transformCommon.stopIterationsS)
	{
		z *= fractal->transformCommon.scale1;
		aux->DE *= fabs(fractal->transformCommon.scale1);
	}
	z -= fractal->transformCommon.offsetF000;

	// Use Identity: native_sqrt(chz^2 + shz^2) = native_sqrt(0.5f * (ez^2 + invEz^2))
	REAL stretch = 1.0;
	if (fractal->transformCommon.functionEnabledNFalse)
	{
		REAL ez2 = ez * ez;
		REAL invEz2 = invEz * invEz;
		stretch = fractal->transformCommon.scaleF1 * native_sqrt(0.5f * (ez2 + invEz2));
		stretch = max(fractal->transformCommon.scaleA1, stretch);
	}

	// 6.f Distance Estimation update
	aux->DE = aux->DE * fractal->analyticDE.scale1 * stretch + fractal->analyticDE.offset0;

	if (fractal->analyticDE.enabled)
	{
		REAL cos_x2 = cx * cx;
		REAL cos_y2 = cy * cy;

		REAL sinh_z2 = shz * shz;
		REAL A = cos_x2 + cos_y2;
		REAL B = cos_x2 * cos_y2;

		// Combined math multiplication multipliers
		REAL S = fractal->transformCommon.scaleG1 * (sinh_z2 * (2.0f + A - B) + A + B) * FRAC_1_3_F;
		//	S = max(S, 0.0f); // nnnnnnnnn 0.5f

		aux->DE *= S;
		aux->DE0 = max(aux->DE0, aux->DE);

		if (aux->i >= fractal->analyticDE.startIterationsA
				&& aux->i < fractal->analyticDE.stopIterationsA)
		{
			aux->dist = 1.0f * 1.0f / native_sqrt(aux->DE0); // scale?
		}
	}
	else
	{
		aux->pseudoKleinianDE = -fractal->transformCommon.offsetR0; // pK DE
	}

	// color
	if (fractal->foldColor.auxColorEnabledFalse && aux->i >= fractal->foldColor.startIterationsA
			&& aux->i < fractal->foldColor.stopIterationsA)
	{
		REAL addCol = fabs(z.x * z.y) * fractal->foldColor.difs0;
		addCol += fractal->foldColor.difs0000.x * stretch + fractal->foldColor.difs0000.y * fabs(z.z)
							+ fractal->foldColor.difs0000.w * fabs(oldZ.z - z.z);
		if (fractal->foldColor.difs0000.z != 0.0f)
			addCol += fractal->foldColor.difs0000.z * length(oldZ - z);

		if (!fractal->foldColor.auxColorEnabledBFalse)
		{
			aux->color += addCol;
		}
		else
		{
			if ((fractal->foldColor.int0 + aux->i) % fractal->foldColor.int2 == 0) aux->color += addCol;
		}
	}
	return z;
}
