/**
 * Mandelbulber v2, a 3D fractal generator  _%}}i*<.        ____                _______
 * Copyright (C) 2017 Mandelbulber Team   _>]|=||i=i<,     / __ \___  ___ ___  / ___/ /
 *                                        \><||i|=>>%)    / /_/ / _ \/ -_) _ \/ /__/ /__
 * This file is part of Mandelbulber.     )<=i=]=|=i<>    \____/ .__/\__/_//_/\___/____/
 * The project is licensed under GPLv3,   -<>>=|><|||`        /_/
 * see also COPYING file in this folder.    ~+{i%+++
 *
 * spherical fold MBox
 */

/* ### This file has been autogenerated. Remove this line, to prevent override. ### */

#ifndef DOUBLE_PRECISION
float4 TransfSphericalFoldIteration(float4 z, __constant sFractalCl *fractal, sExtendedAuxCl *aux)
{
	float r2 = dot(z, z);

	z += fractal->mandelbox.offset;
	z *= fractal->transformCommon.scale;																// beta
	aux->DE = mad(aux->DE, fabs(fractal->transformCommon.scale), 1.0f); // beta
	// if (r2 < 1e-21f) r2 = 1e-21f;
	if (r2 < fractal->mandelbox.mR2)
	{
		z *= fractal->mandelbox.mboxFactor1;
		aux->DE *= fractal->mandelbox.mboxFactor1;
		aux->r_dz *= fractal->mandelbox.mboxFactor1;
		aux->color += fractal->mandelbox.color.factorSp1;
	}
	else if (r2 < fractal->mandelbox.fR2)
	{
		float tglad_factor2 = native_divide(fractal->mandelbox.fR2, r2);
		z *= tglad_factor2;
		aux->DE *= tglad_factor2;
		aux->r_dz *= fractal->mandelbox.mboxFactor1;
		aux->color += fractal->mandelbox.color.factorSp2;
	}
	z -= fractal->mandelbox.offset;
	return z;
}
#else
double4 TransfSphericalFoldIteration(double4 z, __constant sFractalCl *fractal, sExtendedAuxCl *aux)
{
	double r2 = dot(z, z);

	z += fractal->mandelbox.offset;
	z *= fractal->transformCommon.scale;														// beta
	aux->DE = aux->DE * fabs(fractal->transformCommon.scale) + 1.0; // beta
	// if (r2 < 1e-21) r2 = 1e-21;
	if (r2 < fractal->mandelbox.mR2)
	{
		z *= fractal->mandelbox.mboxFactor1;
		aux->DE *= fractal->mandelbox.mboxFactor1;
		aux->r_dz *= fractal->mandelbox.mboxFactor1;
		aux->color += fractal->mandelbox.color.factorSp1;
	}
	else if (r2 < fractal->mandelbox.fR2)
	{
		double tglad_factor2 = native_divide(fractal->mandelbox.fR2, r2);
		z *= tglad_factor2;
		aux->DE *= tglad_factor2;
		aux->r_dz *= fractal->mandelbox.mboxFactor1;
		aux->color += fractal->mandelbox.color.factorSp2;
	}
	z -= fractal->mandelbox.offset;
	return z;
}
#endif
